apiVersion: v1
kind: Service
metadata:
  name: seerai-cicdtest 
  namespace: seerai-system
spec:
  selector:
    app: seerai-cicdtest 
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerai-cicdtest 
  namespace: seerai-system
spec:
  selector:
    matchLabels:
      app: seerai-cicdtest 
  replicas: 2
  template:
    metadata:
      labels:
        app: seerai-cicdtest 
    spec:
      containers:
        - name: seerai-cicdtest 
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          ports:
            - containerPort: 80
              protocol: TCP
